apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myfirstpod
  labels:
    app: flask
spec:
  template:
    metadata:
      name: myfirstpod
      labels:
        app: flask
    spec:
      containers:
        - name: myfirstpod
          image: waseemabushagor/devopswithpy
  replicas: 3
  selector:
    matchLabels:
      app: flask